# ===================================
#  Form Behavior Config
# ===================================

name: system::lang.mail_templates.partial
form: ~/modules/system/models/mailpartial/fields.yaml
modelClass: System\Models\MailPartial
defaultRedirect: system/mailtemplates

create:
    redirect: system/mailpartials/update/:id
    redirectClose: system/mailtemplates

update:
    redirect: system/mailtemplates
    redirectClose: system/mailtemplates
